namespace SuperBasicRPG
{
    enum LightMech
    {
        // Light Mechs: https://www.sarna.net/wiki/Category:Light_BattleMechs
        Adder (Puma), AgroMech (Achernar IndustrialMechs), AgroMech Mk II, Anubis, Arbalest, Arbiter, Arctic Cheetah (Hankyu), Arctic Fox, Arion, Battle Hawk, Bear Cub, Blade, Brigand, Cadaver, Carbine, CattleMaster, Cephalus, Commando, Commando IIC, Copper, Copperhead, Cossack, Cougar, Crimson Hawk, Crosscut, Dart, DemolitionMech, Dig King, Dola, Duan Gung, Eagle, Ebony, Eyrie, Falcon, Falcon Hawk, Fire Ant, Fire Falcon, Fire Moth (Dasher), Fireball, Firebee, Firefly, Firestarter, Flashfire, Flea, Fwltur, Gambit, Garm, Gùn, Gunsmith, Gurkha, Hackman (MechAssault), Hammer, Harvester, Harvester Ant, Havoc, Hedgehog, Hellion, Hermes, Hitman, Hollander, Horned Owl (Peregrine), Hornet, Howler (Baboon), Hussar, Icestorm, Incubus (Vixen), Incubus II, Inquisitor (SecurityMech), Jackal, Jackalope, Jackrabbit, Jaguar, Javelin, Jenner, Jenner IIC, Kabuto, Kit Fox (Uller), Koshi, Koto, Locust, Locust IIC, Longshot, Malak, Mandrill, Mantis, Marco, Mercury, Mist Lynx (Koshi), Mjolnir, MM-1 MiningMech, Mongoose, Morrigan, Nexus, Night Hawk, Nyx, Ocelot, Osiris, Ostscout, Ostscout IIC, Owens, Pacifier, Pack Hunter, Pack Hunter II, Panther, Parash, Pathfinder, Peacemaker (IndustrialMech), Phoenix Hawk L, Piranha, Porcupine, Powerman, Pwwka, Raptor, Rattlesnake, Raven, Razorback, Red Shift, Reptar, Revenant, Rokurokubi, SalvageMech, Scarabus, Shugosha, Silver Fox, Sling, Snow Fox, Sokuryou, Solitaire, Spector, Spider, Spindrift, Spirit, Stiletto, Stinger, Stinger IIC, Stinger LAM, Storm Raider, Super Wasp, Talon, Tarantula, Thorn, Tiburon, Toro, Trooper, UrbanMech, UrbanMech IIC, Valiant, Valkyrie, Venom, Wasp, Wasp LAM, Wight, Wolfhound, Wolfhound IIC, Wulfen, Yinghuochong

    }
    enum MediumMech
    {
        // Medium Mechs: https://www.sarna.net/wiki/Category:Medium_BattleMechs
        Agrotera, Alfar, Anastasia (FrankenMech), Antlion, Apollo, Aquagladius, Araña, Arctic Wolf, Arctic Wolf II, Assassin, Assassin II (MekTek), Avalanche, Bakeneko, Battle Cobra, Belial (MechAssault), Beowulf, Beowulf IIC, Bishamon, Black Hawk, Black Lanner, Blackjack, Blackjack (OmniMech), Blitzkrieg, Bloodhound, Blue Flame, Bombard, Buccaneer, Bushwacker, Buster, Calliope, Centurion, Centurion (OmniMech), Chameleon, Chimera, Cicada, Clint, Clint IIC, Cobra, Conjurer (Hellhound), Corvis, Coyotl, Crab, Crimson Langur, Cronus, Cuirass, Cyllaros, Daedalus, Daimyo, Dark Crow, Dasher II, Dervish, Dervish IIC (MechForce), Drizella (FrankenMech), Eisenfaust, Enfield, Enforcer, Enforcer III, Exhumer, Eyleuka, Fennec, Firestarter (OmniMech), Fox, Gauntlet (OmniMech), Gestalt, Gesu (MekTek), Ghost, Gladiator, Goshawk II, Gravedigger, Great Wyrm, Griffin, Griffin IIC, Grim Reaper, Gyrfalcon, Hatchetman, Hellspawn, Hermes II, Hitotsume Kozo, Hoplite, Hunchback, Hunchback IIC, Huntsman (Nobori-nin), Huron Warrior, Hyena, Icarus II, Ice Ferret (Fenris), Initiate, Inquisitor II (SecurityMech), Jabberwocky, Kheper, Kintaro, Komodo, Kyudo, Legionnaire, Liberator, Lightray, Lineholder, Lobo, Lynx, Mad Cat III, Marshal, Men Shen, Mercury II, Mongoose II, Mongrel, Mongrel (Grendel), Munin LAM, Night Stalker, Nightsky, Nova (Black Hawk), Osprey, Phantom, Phoenix, Phoenix Hawk, Phoenix Hawk LAM, Pinion, Pouncer, Preta, Privateer (MekTek), Prowler, Quasimodo, Quasit, Rabid Coyote, Raider, Raijin, Raptor II, Raven II, Reaver (MekTek), Rock Hound, Ronin, Rook, Sarath, Sarissa, Scarecrow, Scorpion, Scorpion LAM, Screamer, Sentinel, Sentry, Septicemia (Pariah), Sha Yu, Shadow Cat, Shadow Hawk, Shadow Hawk IIC, Shadow Hawk LAM, Shadow-Griffin, Shockwave, Skinwalker (Ryoken III), Slagmaiden, Snake, Stag, Stag II, Stalking Spider, Stalking Spider II, Starslayer, Stealth, Stooping Hawk, Stormcrow (Ryoken), Strider, Sun Cobra, Swordsman, Talos, Targe, Tessen, Thunder Fox, Trebuchet, Tsunami, Ursus, Ursus II, Uziel, Vapor Eagle (Goshawk), Vindicator, Violator, Viper (Dragonfly), Volkh, Vulcan, Waneta, Watchman, Wendigo, Werewolf, Whitworth, Wolf Trap, Wolfman (BattleTechnology BattleMech), Wolverine, Wraith, Wyvern, Wyvern IIC, Yao Lien, Yurei
    }
    enum HeavyMech
    {
        // Heavy Mechs: https://www.sarna.net/wiki/Category:Heavy_BattleMechs
        Anvil, Anzu, Arcas, Archer, Ares (MekTek), Argus, Argus XT (MekTek), Avatar (OmniMech), Axman, Balius, Bandersnatch, Barghest, BattleAxe, Bellerophon, Black Hawk-KU, Black Heart (MekTek), Black Knight, Black Python (Viper), Blood Reaper, Bombardier, Boreas, Bowman, Brahma, Burrock, Caesar, Carronade, Cataphract, Catapult, Catapult II, Cave Lion, Cestus, Champion, Champion LAM, Crossbow, Crossbow (OmniMech), Crusader, Daedalus GTX2, Daikyu, Defiance, Deva, Dig Lord, Dragon, Dragon Fire, Dragon II, Dragoon, Ebon Jaguar (Cauldron-Born), Excalibur, Exterminator, Falconer, Fire Scorpion, Flamberge, Flashman, Galahad, Gallant, Gallowglas, Glass Spider (Galahad), Götterdämmerung, Grand Dragon, Grasshopper, Grigori, Grizzly, Grommet, Guillotine, Guillotine IIC, Ha Otoko, Hachiwara, Hades, Hammerhands, Harpagos, Heavy Lifter, Hector, Helepolis, Helios, Hellbringer (Loki), Hellfire, Hercules, Hound, Jade Hawk, JagerMech, JagerMech III, Jinggau, Karhu, Koschei, Kuma, Lament, Lancelot, Lao Hu, Linebacker, Loki Mk II, Lumberjack, Lupus, Mad Cat Mk IV, Mad Dog (Vulture), Mad Dog II (MekTek), Mad Dog Mk IV (Vulture Mk IV), Maelstrom, Mangonel, Marauder, Matador, Merlin, Minsk, Morpheus, Mortis, Night Gyr, Ninja-To, No-Dachi, Notos, Nova Cat (OmniMech), Onslaught, Orion, Orion IIC, Ostroc, Ostroc Mk II, Ostsol, Ostwar, Paladin, Pandarus, Patriot, Penetrator, Penthesilea, Perseus, Pitbull (MekTek), Predator, Prefect, Prometheus (Unbound), Quickdraw, Rakshasa, Rifleman, Rifleman IIC, Roughneck, Ryoken II, Scourge, Shadow Cat II, Shen Yi, Shiro, Shootist, Shugenja, Sidewinder, Spatha, Sphinx, Summoner (Thor), Sun Spider, Super Griffin, Temax Cat Ninjabolt, Tempest, Tenchi (MekTek), Thanatos, Thanatos XT (MekTek), Thor II, Thresher, Thunder, Thunderbolt, Thunderbolt IIC, Ti Ts'ang, Tian-Zong, Timber Wolf (Mad Cat), Toyama , Triskelion, Tundra Wolf, Uni, Uraeus, Urbanlord, Ursa, Vandal (OmniMech), Verfolger, Von Rohrs , Vulpes, Vulture Mk II, Vulture Mk III, War Dog, Warhammer, Warwolf, White Flame, Wildcat (MekTek), Wildfire, Woodsman, Yeoman
    }
    enum AssaultMech
    {
        // Assault Mechs: https://www.sarna.net/wiki/Category:Assault_BattleMechs
        Akuma, Albatross, Alliance, Annihilator, Archangel, Atlas, Atlas II, Atlas III, Avatar (BattleTechnology), Awesome, Bane (Kraken), Banshee, Banzai, BattleMaster, Berserker, Black Watch, Blood Asp, Blood Kite, Bruin, Bull Shark, Canis, Cerberus, Charger, Colossus, Corsair, Crockett, Cudgel, Cyclops, Cygnus, Daboku, Deimos, Devastator, Diomede, Dire Wolf (Daishi), Doloire, Emperor, Epimetheus, Executioner (Gladiator), Fafnir, Gargoyle (Man O' War), Gausszilla, Goliath, Grand Crusader, Grand Titan, Great Turtle, Gunslinger, Hatamoto-Chi, Hauptmann, HawkWolf, Hellstar, Highlander, Highlander IIC, Huntress , Imp, Juggernaut , Juliano, Jupiter, Katana, King Crab, Kingfisher, Kiso, Kodiak, Kodiak II, Lancer (Wunderwelten), Legacy, Lich, Linesman, Longbow, Lu Wei Bing, Mackie, Mad Cat Mk II, Malice, Marauder II, Marauder IIC, Mauler, Naga (OmniMech), Naginata, Neanderthal, Night Wolf, Nightstar, O-Bakemono, Omen, Onager, Orochi, Osteon, Peacekeeper , Pendragon, Phoenix Hawk IIC, Pillager, Prometheus (MechAssault), Pulverizer, Ragnarok (MechAssault), Rampage, Rifleman II, Rifleman III, Sagittaire, Salamander , Sasquatch, Savage Coyote, Scavenger, Schwerer Gustav, Scylla, Seraph, Shogun, Shrike, Sirocco, Spartan, Stalker, Stalker II, Stone Rhino (Behemoth), Striker , Sunder, Supernova, Tai-Sho , Talos (MekTek), Templar, Templar III, Tenshi, Thug, Thunder Hawk, Thunder Stallion, Titan II, Tomahawk (OmniMech), Tomahawk II, Trebaruna, Turkina, Vampyr, Vanquisher, Victor, Viking, Viking IIC, Wakazashi, Warhammer IIC, Warhawk (Masakari), Warlord, Warthog (MekTek), Xanthos, Ymir, Yu Huang, Zeus, Zeus X
    }
    class Mech
    {
        decimal scriptLevel { get; set; }
        string scriptType { get; set; }
        string scriptName { get; set; }
        string scriptDescription { get; set; }

    }

}